#!/usr/bin/env python3
"""
Seed recipe database with ~40 diverse lunch & dinner recipes.
Designed for a Dutch family — accessible, no weird ingredients, moderate variety.
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
from core import (
    init_db, add_recipe, add_ingredient, add_recipe_ingredient,
    create_plan, generate_12_week_plan,
)

RECIPES = [
    # ====================== DINNERS ======================
    {
        "name": "Geroosterde kipfilet met aardappelen",
        "type": "dinner",
        "cuisine": "Dutch",
        "prep_time": 15, "cook_time": 45, "servings": 4,
        "difficulty": "easy", "tags": "chicken,roast,comfort",
        "ingredients": [
            ("kipfilet", 600, "g", "main", ""),
            ("aardappel", 800, "g", "produce", "geschild en in parten"),
            ("rozemarijn", 2, "takje", "produce", "optioneel"),
            ("knoflook", 2, "teen", "produce", "geperst"),
            ("olijfolie", 15, "ml", "pantry", ""),
            ("peper", 1, "snuf", "pantry", ""),
            ("zout", 1, "snuf", "pantry", ""),
        ],
    },
    {
        "name": "Pasta Bolognese",
        "type": "dinner",
        "cuisine": "Italian",
        "prep_time": 15, "cook_time": 60, "servings": 4,
        "difficulty": "easy", "tags": "pasta,beef,comfort",
        "ingredients": [
            ("rundergehakt", 400, "g", "meat", ""),
            ("pasta", 300, "g", "pantry", "penne of spaghetti"),
            ("tomatensaus", 400, "ml", "pantry", ""),
            ("ui", 1, "stuk", "produce", "gesnipperd"),
            ("knoflook", 2, "teen", "produce", "geperst"),
            ("parmezaanse kaas", 50, "g", "dairy", "geraspt"),
            ("olijfolie", 15, "ml", "pantry", ""),
            ("basilicum", 5, "blad", "produce", "vers, optioneel"),
            ("wortel", 1, "stuk", "produce", "klein gesneden"),
        ],
    },
    {
        "name": "Zalm uit de oven met spinazie",
        "type": "dinner",
        "cuisine": "Scandinavian",
        "prep_time": 10, "cook_time": 20, "servings": 4,
        "difficulty": "easy", "tags": "fish,healthy,quick",
        "ingredients": [
            ("zalmfilet", 500, "g", "meat", ""),
            ("spinazie", 300, "g", "produce", "verse of diepvries"),
            ("citroen", 1, "stuk", "produce", "plakjes"),
            ("roomkaas", 100, "g", "dairy", ""),
            ("aardappel", 600, "g", "produce", "in schil"),
            ("dille", 5, "g", "produce", "vers, optioneel"),
            ("peper", 1, "snuf", "pantry", ""),
            ("zout", 1, "snuf", "pantry", ""),
        ],
    },
    {
        "name": "Indische rijsttafel: Nasi Goreng",
        "type": "dinner",
        "cuisine": "Indonesian",
        "prep_time": 20, "cook_time": 15, "servings": 4,
        "difficulty": "medium", "tags": "spicy,rice,asian",
        "ingredients": [
            ("rijst", 300, "g", "pantry", "gekookt"),
            ("spekreepjes", 150, "g", "meat", "of rookworst"),
            ("ei", 2, "stuk", "dairy", "gebakken"),
            ("ui", 1, "stuk", "produce", "gesnipperd"),
            ("knoflook", 2, "teen", "produce", "geperst"),
            ("ketjap manis", 30, "ml", "pantry", ""),
            ("sambal", 1, "tl", "pantry", ""),
            ("komkommer", 0.5, "stuk", "produce", "in stukjes"),
            ("atjar", 50, "g", "pantry", ""),
        ],
    },
    {
        "name": "Hollandse erwtensoep",
        "type": "dinner",
        "cuisine": "Dutch",
        "prep_time": 15, "cook_time": 90, "servings": 6,
        "difficulty": "easy", "tags": "soup,winter,comfort",
        "ingredients": [
            ("spliterwten", 300, "g", "pantry", "gedroogd"),
            ("rookworst", 300, "g", "meat", ""),
            ("wortel", 2, "stuk", "produce", "in blokjes"),
            ("knolselderij", 200, "g", "produce", "in blokjes"),
            ("ui", 1, "stuk", "produce", "gesnipperd"),
            ("knoflook", 2, "teen", "produce", "geperst"),
            ("speklap", 150, "g", "meat", "optioneel"),
            ("laurel", 2, "blad", "pantry", ""),
            ("peper", 1, "snuf", "pantry", ""),
            ("zout", 1, "snuf", "pantry", ""),
        ],
    },
    {
        "name": "Griekse kip gyros met tzatziki",
        "type": "dinner",
        "cuisine": "Greek",
        "prep_time": 15, "cook_time": 20, "servings": 4,
        "difficulty": "easy", "tags": "chicken,pita,mediterranean",
        "ingredients": [
            ("kipfilet", 500, "g", "meat", "reepjes"),
            ("griekse yoghurt", 200, "g", "dairy", ""),
            ("komkommer", 1, "stuk", "produce", "geraspt"),
            ("knoflook", 2, "teen", "produce", "geperst"),
            ("olijfolie", 15, "ml", "pantry", ""),
            ("paprika", 2, "stuk", "produce", "in reepjes"),
            ("rode ui", 1, "stuk", "produce", "in halve ringen"),
            ("gyroskruiden", 10, "g", "pantry", ""),
            ("pitabroodje", 4, "stuk", "bakery", ""),
        ],
    },
    {
        "name": "Thaise groene curry met kip",
        "type": "dinner",
        "cuisine": "Thai",
        "prep_time": 10, "cook_time": 25, "servings": 4,
        "difficulty": "medium", "tags": "spicy,coconut,asian",
        "ingredients": [
            ("kipfilet", 500, "g", "meat", "reepjes"),
            ("kokosmelk", 400, "ml", "pantry", ""),
            ("groene curry pasta", 50, "g", "pantry", ""),
            ("babymais", 150, "g", "produce", ""),
            ("snijbonen", 150, "g", "produce", ""),
            ("thaise basilicum", 10, "g", "produce", "optioneel"),
            ("aubergine", 1, "stuk", "produce", "in blokjes"),
            ("rijst", 300, "g", "pantry", ""),
            ("limoen", 1, "stuk", "produce", ""),
        ],
    },
    {
        "name": "Mexicaanse burrito bowl",
        "type": "dinner",
        "cuisine": "Mexican",
        "prep_time": 20, "cook_time": 20, "servings": 4,
        "difficulty": "easy", "tags": "tex-mex,healthy,customizable",
        "ingredients": [
            ("rijst", 300, "g", "pantry", ""),
            ("bonenmix", 400, "g", "pantry", ""),
            ("maïs", 200, "g", "pantry", ""),
            ("kipfilet", 400, "g", "meat", "reepjes"),
            ("paprika", 2, "stuk", "produce", "in blokjes"),
            ("avocado", 2, "stuk", "produce", ""),
            ("limoen", 1, "stuk", "produce", ""),
            ("jalapeño", 1, "stuk", "produce", "optioneel"),
            ("salsa", 100, "g", "pantry", ""),
            ("cumin", 1, "tl", "pantry", ""),
            ("griekse yoghurt", 100, "g", "dairy", "als topping"),
        ],
    },
    {
        "name": "Gekarameliseerde ui quiche",
        "type": "dinner",
        "cuisine": "French",
        "prep_time": 20, "cook_time": 50, "servings": 4,
        "difficulty": "medium", "tags": "vegetarian,comfort",
        "ingredients": [
            ("ui", 500, "g", "produce", "gesneden"),
            ("eieren", 4, "stuk", "dairy", ""),
            ("creme fraiche", 200, "ml", "dairy", ""),
            ("feta kaas", 100, "g", "dairy", "in kruimels"),
            ("boter", 50, "g", "dairy", ""),
            ("salade", 200, "g", "produce", "als bijgerecht"),
            ("zout", 1, "snuf", "pantry", ""),
            ("peper", 1, "snuf", "pantry", ""),
        ],
    },
    {
        "name": "Hachee met rode kool en aardappelpuree",
        "type": "dinner",
        "cuisine": "Dutch",
        "prep_time": 15, "cook_time": 90, "servings": 4,
        "difficulty": "easy", "tags": "beef,stew,comfort,winter",
        "ingredients": [
            ("rundergehakt", 500, "g", "meat", ""),
            ("aardappel", 800, "g", "produce", "puree"),
            ("melk", 200, "ml", "dairy", ""),
            ("boter", 50, "g", "dairy", ""),
            ("rode kool", 500, "g", "produce", "kant-en-klaar"),
            ("ui", 2, "stuk", "produce", "gesnipperd"),
            ("laurel", 2, "blad", "pantry", ""),
            ("appelstroop", 15, "ml", "pantry", ""),
            ("peper", 1, "snuf", "pantry", ""),
            ("zout", 1, "snuf", "pantry", ""),
        ],
    },
    {
        "name": "Visstoofpotje met kabeljauw",
        "type": "dinner",
        "cuisine": "Belgian",
        "prep_time": 15, "cook_time": 30, "servings": 4,
        "difficulty": "medium", "tags": "fish,comfort,one-pot",
        "ingredients": [
            ("kabeljauwfilet", 500, "g", "meat", ""),
            ("prei", 1, "stuk", "produce", "in ringen"),
            ("ui", 1, "stuk", "produce", "gesnipperd"),
            ("aardappel", 500, "g", "produce", "in blokjes"),
            ("room", 100, "ml", "dairy", ""),
            ("visbouillon", 300, "ml", "pantry", ""),
            ("peterselie", 10, "g", "produce", ""),
            ("peper", 1, "snuf", "pantry", ""),
            ("zout", 1, "snuf", "pantry", ""),
        ],
    },
    {
        "name": "Pulled pork uit de slowcooker",
        "type": "dinner",
        "cuisine": "American",
        "prep_time": 15, "cook_time": 360, "servings": 6,
        "difficulty": "easy", "tags": "pork,comfort,bbq",
        "ingredients": [
            ("varkensschouder", 1200, "g", "meat", ""),
            ("ui", 1, "stuk", "produce", "gesnipperd"),
            ("appelciderazijn", 60, "ml", "pantry", ""),
            ("knoflook", 4, "teen", "produce", "geperst"),
            ("paprikapoeder", 15, "g", "pantry", ""),
            ("bruine suiker", 30, "g", "pantry", ""),
            ("broodje wit", 6, "stuk", "bakery", ""),
            ("ijsbergsla", 200, "g", "produce", ""),
            ("coleslaw", 200, "g", "pantry", ""),
        ],
    },
    {
        "name": "Schnitzel met geroosterde paprika",
        "type": "dinner",
        "cuisine": "German",
        "prep_time": 10, "cook_time": 20, "servings": 4,
        "difficulty": "easy", "tags": "pork,quick",
        "ingredients": [
            ("varkenshaas", 600, "g", "meat", "in plakken"),
            ("paneermeel", 100, "g", "pantry", ""),
            ("ei", 1, "stuk", "dairy", "losgeklopt"),
            ("bloem", 50, "g", "pantry", ""),
            ("paprika", 4, "stuk", "produce", "in reepjes"),
            ("aardappel", 600, "g", "produce", "friet of gestoofd"),
            ("olijfolie", 15, "ml", "pantry", ""),
            ("citrussalade", 150, "g", "produce", "optioneel"),
        ],
    },
    {
        "name": "Vegetarische linzenstoofschotel",
        "type": "dinner",
        "cuisine": "Middle Eastern",
        "prep_time": 10, "cook_time": 40, "servings": 4,
        "difficulty": "easy", "tags": "vegetarian,healthy,comfort",
        "ingredients": [
            ("groene linzen", 250, "g", "pantry", "uitgelekt"),
            ("passata", 400, "ml", "pantry", ""),
            ("wortel", 2, "stuk", "produce", "in blokjes"),
            ("ui", 1, "stuk", "produce", "gesnipperd"),
            ("knoflook", 3, "teen", "produce", "geperst"),
            ("spinazie", 200, "g", "produce", "verse"),
            ("feta kaas", 100, "g", "dairy", "in kruimels"),
            ("komijn", 1, "tl", "pantry", ""),
            ("aardappel", 600, "g", "produce", ""),
            ("citroen", 1, "stuk", "produce", ""),
        ],
    },
    {
        "name": "Ramen met kip",
        "type": "dinner",
        "cuisine": "Japanese",
        "prep_time": 15, "cook_time": 30, "servings": 4,
        "difficulty": "medium", "tags": "soup,noodles,comfort",
        "ingredients": [
            ("kipfilet", 300, "g", "meat", "in reepjes"),
            ("ramen noodles", 300, "g", "pantry", ""),
            ("chicken broth", 1000, "ml", "pantry", ""),
            ("ei", 2, "stuk", "dairy", "zacht gekookt"),
            ("paksoi", 200, "g", "produce", "in stukken"),
            ("sojasaus", 30, "ml", "pantry", ""),
            ("sesamolie", 10, "ml", "pantry", ""),
            ("bosui", 2, "stuk", "produce", ""),
            ("ginger", 20, "g", "produce", "fijngehakt"),
            ("corn", 50, "g", "pantry", ""),
        ],
    },
    {
        "name": "Paella Valencia",
        "type": "dinner",
        "cuisine": "Spanish",
        "prep_time": 20, "cook_time": 40, "servings": 4,
        "difficulty": "medium", "tags": "rice,seafood",
        "ingredients": [
            ("rijst", 300, "g", "pantry", ""),
            ("gamba's", 300, "g", "meat", ""),
            ("kippenpoot", 2, "stuk", "meat", ""),
            ("chorizo", 100, "g", "meat", "in plakjes"),
            ("paprika", 1, "stuk", "produce", "in blokjes"),
            ("ui", 1, "stuk", "produce", "gesnipperd"),
            ("knoflook", 3, "teen", "produce", "geperst"),
            ("kippenbouillon", 750, "ml", "pantry", ""),
            ("saffraan", 1, "snuf", "pantry", ""),
            ("erwtjes", 100, "g", "frozen", ""),
            ("citroen", 1, "stuk", "produce", "plakjes"),
        ],
    },
    {
        "name": "Pad Thai met garnalen",
        "type": "dinner",
        "cuisine": "Thai",
        "prep_time": 20, "cook_time": 15, "servings": 4,
        "difficulty": "medium", "tags": "noodles,seafood,spicy",
        "ingredients": [
            ("rijstnoedels", 250, "g", "pantry", ""),
            ("garnalen", 300, "g", "meat", ""),
            ("ei", 2, "stuk", "dairy", ""),
            ("tamarinde pasta", 30, "g", "pantry", ""),
            ("bosui", 3, "stuk", "produce", ""),
            ("spruitjes", 100, "g", "produce", ""),
            ("limoen", 1, "stuk", "produce", ""),
            ("pinda's", 30, "g", "pantry", "gehakt"),
            ("palm suiker", 15, "g", "pantry", ""),
            ("olijfolie", 15, "ml", "pantry", ""),
        ],
    },
    {
        "name": "Stoofvlees van rund met bier",
        "type": "dinner",
        "cuisine": "Belgian",
        "prep_time": 20, "cook_time": 120, "servings": 4,
        "difficulty": "easy", "tags": "beef,comfort,winter,stew",
        "ingredients": [
            ("rundsvlees", 700, "g", "meat", "in blokjes"),
            ("bier", 330, "ml", "pantry", "donker"),
            ("ui", 2, "stuk", "produce", "gesnipperd"),
            ("bloem", 30, "g", "pantry", ""),
            ("peper", 1, "snuf", "pantry", ""),
            ("zout", 1, "snuf", "pantry", ""),
            ("laurel", 2, "blad", "pantry", ""),
            ("friet aardappel", 800, "g", "frozen", ""),
            ("mayonaise", 50, "g", "pantry", ""),
        ],
    },
    {
        "name": "Falafel salade bowl",
        "type": "dinner",
        "cuisine": "Levantine",
        "prep_time": 10, "cook_time": 10, "servings": 4,
        "difficulty": "easy", "tags": "vegetarian,quick,healthy",
        "ingredients": [
            ("falafelballetjes", 300, "g", "frozen", "of vers"),
            ("bulgur", 200, "g", "pantry", "gekookt"),
            ("komkommer", 1, "stuk", "produce", ""),
            ("tomaat", 2, "stuk", "produce", ""),
            ("rode ui", 0.5, "stuk", "produce", ""),
            ("tahini", 30, "ml", "pantry", ""),
            ("citroen", 1, "stuk", "produce", ""),
            ("knoflook", 1, "teen", "produce", ""),
            ("chili vlokken", 1, "snuf", "pantry", ""),
            ("peterselie", 10, "g", "produce", ""),
        ],
    },
    {
        "name": "Moussaka",
        "type": "dinner",
        "cuisine": "Greek",
        "prep_time": 30, "cook_time": 60, "servings": 4,
        "difficulty": "medium", "tags": "beef,aubergine,comfort",
        "ingredients": [
            ("aubergine", 2, "stuk", "produce", "in plakken"),
            ("rundergehakt", 400, "g", "meat", ""),
            ("aardappel", 400, "g", "produce", "in plakjes"),
            ("ei", 2, "stuk", "dairy", ""),
            ("griekse yoghurt", 200, "g", "dairy", ""),
            ("tomatensaus", 300, "ml", "pantry", ""),
            ("ui", 1, "stuk", "produce", "gesnipperd"),
            ("knoflook", 2, "teen", "produce", "geperst"),
            ("cinnamon", 1, "snuf", "pantry", ""),
            ("parmezaanse kaas", 50, "g", "dairy", ""),
        ],
    },
    {
        "name": "Chili con carne",
        "type": "dinner",
        "cuisine": "Tex-Mex",
        "prep_time": 15, "cook_time": 60, "servings": 4,
        "difficulty": "easy", "tags": "spicy,beef,comfort",
        "ingredients": [
            ("rundergehakt", 500, "g", "meat", ""),
            ("kidney bonen", 400, "g", "pantry", ""),
            ("tomatensaus", 400, "ml", "pantry", ""),
            ("ui", 1, "stuk", "produce", "gesnipperd"),
            ("knoflook", 3, "teen", "produce", "geperst"),
            ("chili poeder", 15, "g", "pantry", ""),
            ("cumin", 1, "tl", "pantry", ""),
            ("cacaopoeder", 5, "g", "pantry", ""),
            ("rijst", 300, "g", "pantry", ""),
            ("kaas", 50, "g", "dairy", "geraspt"),
            ("cilantro", 10, "g", "produce", ""),
        ],
    },

    # ====================== LUNCHES ======================
    {
        "name": "Tonijnsalade sandwich",
        "type": "lunch",
        "cuisine": "Dutch",
        "prep_time": 10, "cook_time": 0, "servings": 4,
        "difficulty": "easy", "tags": "cold,quick,sandwich",
        "ingredients": [
            ("tonijn uit blik", 300, "g", "pantry", ""),
            ("mayonaise", 60, "g", "pantry", ""),
            ("peterselie", 5, "g", "produce", "fijngehakt"),
            ("citroensap", 15, "ml", "pantry", ""),
            ("pain de mie", 8, "stuk", "bakery", ""),
            ("sla", 100, "g", "produce", ""),
            ("tomaat", 1, "stuk", "produce", "in plakjes"),
            ("komkommer", 0.5, "stuk", "produce", ""),
        ],
    },
    {
        "name": "Rijsttafel salade met saté",
        "type": "lunch",
        "cuisine": "Indonesian",
        "prep_time": 15, "cook_time": 10, "servings": 4,
        "difficulty": "easy", "tags": "cold,salad,asian",
        "ingredients": [
            ("rijst", 200, "g", "pantry", "gekookt en afgekoeld"),
            ("saté saus", 100, "ml", "pantry", ""),
            ("gurkensalade", 100, "g", "pantry", ""),
            ("bamba", 50, "g", "pantry", ""),
            ("gekookt ei", 2, "stuk", "dairy", ""),
            ("sla", 100, "g", "produce", ""),
            ("ui", 0.5, "stuk", "produce", ""),
            ("komkommer", 0.5, "stuk", "produce", ""),
        ],
    },
    {
        "name": "Wrap met hummus en gegrilde groente",
        "type": "lunch",
        "cuisine": "Mediterranean",
        "prep_time": 10, "cook_time": 10, "servings": 4,
        "difficulty": "easy", "tags": "vegetarian,wrap",
        "ingredients": [
            ("wraps", 4, "stuk", "bakery", ""),
            ("hummus", 200, "g", "pantry", ""),
            ("paprika", 2, "stuk", "produce", "in reepjes"),
            ("courgette", 1, "stuk", "produce", "in plakjes"),
            ("rode ui", 0.5, "stuk", "produce", ""),
            ("feta kaas", 50, "g", "dairy", ""),
            ("rucola", 50, "g", "produce", ""),
            ("olijfolie", 15, "ml", "pantry", ""),
        ],
    },
    {
        "name": "Omelet met spinazie en geitenkaas",
        "type": "lunch",
        "cuisine": "French",
        "prep_time": 5, "cook_time": 10, "servings": 4,
        "difficulty": "easy", "tags": "eggs,quick,vegetarian",
        "ingredients": [
            ("eieren", 6, "stuk", "dairy", ""),
            ("spinazie", 200, "g", "produce", "verse"),
            ("geitenkaas", 100, "g", "dairy", "in kruimels"),
            ("peper", 1, "snuf", "pantry", ""),
            ("zout", 1, "snuf", "pantry", ""),
            ("boter", 20, "g", "dairy", ""),
        ],
    },
    {
        "name": "Leftover nasi met ei",
        "type": "lunch",
        "cuisine": "Indonesian",
        "prep_time": 5, "cook_time": 8, "servings": 4,
        "difficulty": "easy", "tags": "leftover,rice,quick",
        "ingredients": [
            ("overgebleven rijst", 400, "g", "pantry", ""),
            ("ei", 2, "stuk", "dairy", "gebakken"),
            ("ui", 0.5, "stuk", "produce", ""),
            ("knoflook", 1, "teen", "produce", ""),
            ("ketjap", 15, "ml", "pantry", ""),
            ("chili", 1, "stuk", "produce", "optioneel"),
        ],
    },
    {
        "name": "Tomatensoep met kaasbroodjes",
        "type": "lunch",
        "cuisine": "Dutch",
        "prep_time": 5, "cook_time": 15, "servings": 4,
        "difficulty": "easy", "tags": "soup,comfort",
        "ingredients": [
            ("tomatensoep", 1, "liter", "pantry", "vers"),
            ("baguette", 1, "stuk", "bakery", ""),
            ("geraspte kaas", 100, "g", "dairy", ""),
            ("bosui", 2, "stuk", "produce", ""),
            ("creme fraiche", 50, "g", "dairy", "dollop"),
        ],
    },
    {
        "name": "Avocado toast met gerookte zalm",
        "type": "lunch",
        "cuisine": "Modern",
        "prep_time": 10, "cook_time": 0, "servings": 4,
        "difficulty": "easy", "tags": "cold,healthy,no-cook",
        "ingredients": [
            ("volkoren brood", 4, "stuk", "bakery", "gesneden"),
            ("avocado", 2, "stuk", "produce", "prak"),
            ("gerookte zalm", 200, "g", "meat", ""),
            ("citroensap", 15, "ml", "pantry", ""),
            ("bosui", 1, "stuk", "produce", ""),
            ("chili vlokken", 1, "snuf", "pantry", ""),
            ("peper", 1, "snuf", "pantry", ""),
        ],
    },
    {
        "name": "Griekse salade met feta",
        "type": "lunch",
        "cuisine": "Greek",
        "prep_time": 10, "cook_time": 0, "servings": 4,
        "difficulty": "easy", "tags": "cold,salad,healthy",
        "ingredients": [
            ("tomaat", 4, "stuk", "produce", ""),
            ("komkommer", 2, "stuk", "produce", ""),
            ("rode ui", 0.5, "stuk", "produce", ""),
            ("olijven", 50, "g", "pantry", ""),
            ("feta kaas", 150, "g", "dairy", ""),
            ("olijfolie", 30, "ml", "pantry", ""),
            ("oregano", 1, "snuf", "pantry", ""),
            ("pitabroodje", 2, "stuk", "bakery", ""),
        ],
    },
    {
        "name": "Broodje balletjes in tomatensaus",
        "type": "lunch",
        "cuisine": "Dutch",
        "prep_time": 5, "cook_time": 15, "servings": 4,
        "difficulty": "easy", "tags": "sandwich,comfort,quick",
        "ingredients": [
            ("gehaktballetjes", 400, "g", "frozen", ""),
            ("tomatensaus", 300, "ml", "pantry", ""),
            ("pitabroodje", 4, "stuk", "bakery", ""),
            ("kaas", 80, "g", "dairy", "gesneden"),
            ("sla", 50, "g", "produce", ""),
        ],
    },
    {
        "name": "Quinoa salade met gegrilde kip",
        "type": "lunch",
        "cuisine": "Modern",
        "prep_time": 15, "cook_time": 15, "servings": 4,
        "difficulty": "easy", "tags": "salad,healthy,protein",
        "ingredients": [
            ("quinoa", 200, "g", "pantry", "gekookt"),
            ("kipfilet", 250, "g", "meat", "in reepjes"),
            ("paprika", 1, "stuk", "produce", "in blokjes"),
            ("maïs", 100, "g", "pantry", ""),
            ("spinazie", 100, "g", "produce", ""),
            ("limoen", 1, "stuk", "produce", ""),
            ("olijfolie", 15, "ml", "pantry", ""),
            ("komkommer", 1, "stuk", "produce", ""),
        ],
    },
    {
        "name": "Broodje Surinaamse kip kerrie",
        "type": "lunch",
        "cuisine": "Surinamese",
        "prep_time": 10, "cook_time": 10, "servings": 4,
        "difficulty": "easy", "tags": "spicy,sandwich,quick",
        "ingredients": [
            ("kipfilet", 300, "g", "meat", "in reepjes"),
            ("kerriepoeder", 10, "g", "pantry", ""),
            ("ui", 0.5, "stuk", "produce", ""),
            ("knoflook", 1, "teen", "produce", ""),
            ("broodje", 4, "stuk", "bakery", ""),
            ("sla", 50, "g", "produce", ""),
            ("tomaat", 1, "stuk", "produce", ""),
            ("taugé", 50, "g", "produce", "optioneel"),
            ("madame jeanette peper", 1, "stuk", "produce", "optioneel"),
        ],
    },
    {
        "name": "Toast Hawaii deluxe",
        "type": "lunch",
        "cuisine": "Dutch",
        "prep_time": 5, "cook_time": 15, "servings": 4,
        "difficulty": "easy", "tags": "toast,comfort,kid-friendly",
        "ingredients": [
            ("wit brood", 4, "stuk", "bakery", ""),
            ("gekookte ham", 200, "g", "meat", ""),
            ("kaas", 120, "g", "dairy", ""),
            ("ananas uit blik", 4, "ring", "pantry", ""),
            ("zoete chili saus", 30, "ml", "pantry", "optioneel"),
        ],
    },
    {
        "name": "Salade Niçoise",
        "type": "lunch",
        "cuisine": "French",
        "prep_time": 15, "cook_time": 10, "servings": 4,
        "difficulty": "easy", "tags": "salad,eggs,tuna",
        "ingredients": [
            ("haricots verts", 150, "g", "produce", "gekookt"),
            ("tonijn uit blik", 200, "g", "pantry", ""),
            ("ei", 4, "stuk", "dairy", "gekookt"),
            ("tomaat", 4, "stuk", "produce", ""),
            ("aardappel", 300, "g", "produce", "gekookt in schil"),
            ("zwarte olijven", 50, "g", "pantry", ""),
            ("sla", 100, "g", "produce", ""),
            ("azijn dressing", 30, "ml", "pantry", ""),
        ],
    },
    {
        "name": "Pastasalade pesto kip",
        "type": "lunch",
        "cuisine": "Italian",
        "prep_time": 10, "cook_time": 15, "servings": 4,
        "difficulty": "easy", "tags": "pasta,cold,comfort",
        "ingredients": [
            ("fusilli pasta", 300, "g", "pantry", ""),
            ("kipfilet", 200, "g", "meat", "gekookt in reepjes"),
            ("pestosaus", 100, "g", "pantry", ""),
            ("pijnboompit", 20, "g", "pantry", ""),
            ("cherrytomaat", 200, "g", "produce", ""),
            ("mozzarella bolletjes", 125, "g", "dairy", ""),
            ("peper", 1, "snuf", "pantry", ""),
        ],
    },
    {
        "name": "Aardappel-ansjovis salade",
        "type": "lunch",
        "cuisine": "French",
        "prep_time": 10, "cook_time": 15, "servings": 4,
        "difficulty": "easy", "tags": "cold,salad,fish",
        "ingredients": [
            ("aardappel", 500, "g", "produce", "gekookt in schil"),
            ("witte ansjovis", 100, "g", "pantry", ""),
            ("ui", 1, "stuk", "produce", "gesnipperd"),
            ("peterselie", 10, "g", "produce", ""),
            ("zonnebloemolie", 30, "ml", "pantry", ""),
            ("azijn", 15, "ml", "pantry", ""),
            ("peper", 1, "snuf", "pantry", ""),
        ],
    },
    {
        "name": "Taco bowl",
        "type": "lunch",
        "cuisine": "Mexican",
        "prep_time": 15, "cook_time": 10, "servings": 4,
        "difficulty": "easy", "tags": "rice,spicy,healthy",
        "ingredients": [
            ("rijst", 200, "g", "pantry", ""),
            ("gekruid gehakt", 250, "g", "meat", ""),
            ("salsa", 100, "g", "pantry", ""),
            ("maïs", 100, "g", "pantry", ""),
            ("tomaat", 2, "stuk", "produce", ""),
            ("avocado", 1, "stuk", "produce", ""),
            ("cheddar", 50, "g", "dairy", "geraspt"),
            ("sla", 100, "g", "produce", ""),
            ("tortilla", 4, "stuk", "bakery", ""),
        ],
    },
    {
        "name": "Zuurkoolsalade met mandarijn",
        "type": "lunch",
        "cuisine": "Dutch",
        "prep_time": 10, "cook_time": 0, "servings": 4,
        "difficulty": "easy", "tags": "cold,salad,dutch",
        "ingredients": [
            ("zuurkool", 200, "g", "pantry", "uitgeknepen"),
            ("mandarijn", 2, "stuk", "produce", "in stukjes"),
            ("spekjes", 100, "g", "meat", "gebakken"),
            ("walnoten", 30, "g", "pantry", ""),
            ("dijon mosterd", 15, "g", "pantry", ""),
            ("mayonaise", 30, "g", "pantry", ""),
            ("sla", 100, "g", "produce", ""),
        ],
    },
    {
        "name": "Spaanse tortilla (tortilla Española)",
        "type": "lunch",
        "cuisine": "Spanish",
        "prep_time": 10, "cook_time": 20, "servings": 4,
        "difficulty": "easy", "tags": "eggs,vegetarian,comfort",
        "ingredients": [
            ("aardappel", 400, "g", "produce", "in plakjes"),
            ("ei", 5, "stuk", "dairy", ""),
            ("ui", 1, "stuk", "produce", "gesnipperd"),
            ("olijfolie", 30, "ml", "pantry", ""),
            ("zout", 1, "snuf", "pantry", ""),
            ("peper", 1, "snuf", "pantry", ""),
        ],
    },
    {
        "name": "Wrap met rosbief en mosterd dressing",
        "type": "lunch",
        "cuisine": "Dutch",
        "prep_time": 5, "cook_time": 0, "servings": 4,
        "difficulty": "easy", "tags": "cold,sandwich,quick",
        "ingredients": [
            ("wraps", 4, "stuk", "bakery", ""),
            ("rosbief", 200, "g", "meat", "gesneden"),
            ("rucola", 50, "g", "produce", ""),
            ("tomaat", 1, "stuk", "produce", ""),
            ("mosterd dressing", 30, "ml", "pantry", ""),
            ("maïs", 50, "g", "pantry", ""),
            ("komkommer", 0.5, "stuk", "produce", ""),
        ],
    },
    {
        "name": "Japanse koude soba noodles",
        "type": "lunch",
        "cuisine": "Japanese",
        "prep_time": 10, "cook_time": 10, "servings": 4,
        "difficulty": "easy", "tags": "noodles,cold,asian",
        "ingredients": [
            ("soba noodles", 250, "g", "pantry", ""),
            ("sojasaus", 30, "ml", "pantry", ""),
            ("mirin", 15, "ml", "pantry", ""),
            ("sesamolie", 10, "ml", "pantry", ""),
            ("komkommer", 1, "stuk", "produce", "julienne"),
            ("taugé", 50, "g", "produce", ""),
            ("bosui", 2, "stuk", "produce", ""),
            ("wasabi", 5, "g", "pantry", ""),
            ("sesam zaadjes", 10, "g", "pantry", ""),
        ],
    },
]


# ======== Staples that always appear in shopping =========
STAPLES = [
    ("olijfolie", "pantry", "ml", None, 1, "olijfolie"),
    ("boter", "dairy", "g", 30, 1, "zuivel"),
    ("melk", "dairy", "ml", 7, 1, "zuivel"),
    ("eieren", "dairy", "stuk", 21, 1, "zuivel"),
    ("zout", "pantry", "g", None, 1, "kruiden"),
    ("peper", "pantry", "g", None, 1, "kruiden"),
    ("bloem", "pantry", "g", None, 0, "bakproducten"),
    ("paprikapoeder", "pantry", "g", None, 1, "kruiden"),
    ("chili poeder", "pantry", "g", None, 1, "kruiden"),
    ("cumin", "pantry", "g", None, 1, "kruiden"),
]


def seed():
    init_db()
    print("Seeding ingredients...")
    # Seed all ingredients first (canonical list)
    ing_map = {}
    seen = set()
    for r in RECIPES:
        for (iname, _, unit, cat, _) in r["ingredients"]:
            key = iname.lower()
            if key in seen:
                continue
            seen.add(key)
            iid = add_ingredient(
                name=iname,
                category=cat,
                default_unit=unit,
                store_section=cat or "overig",
            )
            ing_map[key] = iid

    # Seed staples
    for name, cat, unit, shelf, staple, section in STAPLES:
        key = name.lower()
        if key in seen:
            continue
        seen.add(key)
        add_ingredient(name=name, category=cat, default_unit=unit, shelf_life_days=shelf, staple=staple, store_section=section)

    print("Seeding recipes...")
    recipe_ids = {"dinner": [], "lunch": []}
    for r in RECIPES:
        rid = add_recipe(
            name=r["name"],
            type_=r["type"],
            cuisine=r["cuisine"],
            prep_time=r["prep_time"],
            cook_time=r["cook_time"],
            servings=r["servings"],
            difficulty=r["difficulty"],
            tags=r["tags"],
        )
        recipe_ids[r["type"]].append(rid)
        for (iname, qty, unit, _, prep) in r["ingredients"]:
            iid = ing_map[iname.lower()]
            add_recipe_ingredient(rid, iid, qty, unit, prep)

    print(f"Seeded {len(recipe_ids['dinner'])} dinners, {len(recipe_ids['lunch'])} lunches.")

    print("Creating 12-week meal plan...")
    plan_id = create_plan("vdM Home — 12 Week Rotation")
    generate_12_week_plan(plan_id, recipe_ids["dinner"], recipe_ids["lunch"], strategy="rotation")
    print(f"Plan {plan_id} ready.")


if __name__ == "__main__":
    seed()
